# Codecov configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        # Overall project coverage target (excluding TUI)
        target: 90%
        threshold: 2%
        informational: false
    patch:
      default:
        # New code coverage target
        target: 80%
        threshold: 5%
        informational: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  # Exclude interactive TUI code from coverage requirements
  - "src/rostree/tui/**"
